version: 0.2
#env:
  #variables:
   # BranchName: $BranchName
  #parameter-store:
    #STAGE_DEV: STAGE
    #DB_PASSWORD: DB_PASSWORD

phases:
   install:
      commands:
         - echo "install stage"
   build:
      commands:
         - echo "build step"
   post_build:
      commands:
         - echo $CODEBUILD_WEBHOOK_HEAD_REF
         - echo $BranchName
         - if [ [ $CODEBUILD_WEBHOOK_HEAD_REF = "refs/heads/develop" ] || [ $BranchName = "develop" ] ]; then 
              NODE_ENV="dev"; 
           fi # elif [ ["$CODEBUILD_WEBHOOK_HEAD_REF" = "refs/heads/stage"] || ["$BranchName" = "stage"] ]; then NODE_ENV="stage"; elif [ ["$CODEBUILD_WEBHOOK_HEAD_REF" = "refs/heads/master"] || ["$BranchName" = "master"] ]; then NODE_ENV="prod"; fi
         #- if [ "$BranchName" = "develop" ]; then NODE_ENV="dev"; elif [ "$BranchName" = "stage" ]; then NODE_ENV="stage"; elif [ "$BranchName" = "master" ]; then NODE_ENV="prod"; fi
         - echo "deploying for NODE_DEV = $NODE_ENV"
         - if [ $NODE_ENV = "prod" ]; then tableEnv="production"; else tableEnv="$NODE_ENV"; fi
         - echo $STAGE
         - echo $DB_PASSWORD
         - echo $tableEnv
         - echo $BranchName
         - echo "$SHELL"
         
