version: 0.2

phases:
   install:
      commands:
         - echo "install stage"
   build:
      commands:
         - echo "build step"
   post_build:
      commands:
         - env="dev"
        
         - echo $CODEBUILD_WEBHOOK_HEAD_REF
         - if [ "$CODEBUILD_WEBHOOK_HEAD_REF" = "refs/heads/master" ]; then env="prod"; elif [ "$CODEBUILD_WEBHOOK_HEAD_REF" = "refs/heads/develop" ]; then env="dev"; elif [ "$CODEBUILD_WEBHOOK_HEAD_REF" = "refs/heads/stage" ]; then env="stage"; fi
         - echo $STAGE
          - echo $CODEBUILD_WEBHOOK_HEAD_REF
