version: 0.2
env:
  variables:
    CODEBUILD_WEBHOOK_HEAD_REF: CODEBUILD_WEBHOOK_HEAD_REF
  parameter-store:
    STAGE_DEV: STAGE
    DB_PASSWORD: DB_PASSWORD

phases:
   install:
      commands:
         - echo "install stage"
   build:
      commands:
         - echo "build step"
   post_build:
      commands:
         - echo $CODEBUILD_WEBHOOK_HEAD_REF
         - echo $STAGE_DEV
         - echo $DB_PASSWORD
